export default {
  preset: 'ts-jest/presets/js-with-babel',
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif)$': 'identity-obj-proxy',
    '^@config/envs$': '<rootDir>/src/__mocks__/envs.mock.ts',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@redux/(.*)$': '<rootDir>/src/redux/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@service/(.*)$': '<rootDir>/src/service/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  bail: 20,
  verbose: true,
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/*',
    '<rootDir>/build/*',
    '<rootDir>/redux/*',
  ],
}
